### PR TITLE
Use CACHE_NAME in sw example fetch

### PR DESCRIPTION
**Pull request by st4lk**
Try to find request in cache with `CACHE_NAME`, not in global cache

### CODE REVIEW

**Comment by woutervanvliet** [comment]
Why exactly would you want to look at a specific cache, and not "all caches" when trying to match a request?

The 'activate' event handler takes care of cleaning up old caches, so you should be sure at the time of a 'fetch' event that there's nothing stale hanging around.

**Comment by st4lk** [comment]
@woutervanvliet 
The resources were cached in specific `CACHE_NAME` cache in `install` event. `fetch` event should check that cache (the resource is not present in global cache)

**Comment by woutervanvliet** [comment]
Indeed, they are added to the cache by that name. But that makes them available to be found through any `caches.match`, not just the specific cache it was added to.

Since the event handler for activate looks at which caches have been created, and deletes all but the "currently active one", this would be pretty safe.

A scenario where you might want to look in a specific cache, is if you base the cache name on some kind of user-login state. But that would, imho, be far out of scope of example on how to use this plugin.

**Comment by st4lk** [comment]
Not sure, maybe you are right. I just tried to play with it locally, and as I remember it didn't work with global cache. Will check again

This resources have examples with `fetch` and specific cache:

https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#on-network-response

https://serviceworke.rs/

**Comment by oliviertassinari** [comment]
What do you guys think of removing the custom logic of the documentation to rely on [workbox](https://developers.google.com/web/tools/workbox/next/)? We have been configuring it for Material-UI. It's working great: https://github.com/mui-org/material-ui/blob/v1-beta/docs/src/sw.js.

**Comment by woutervanvliet** [comment]
Would have no objections against *also* having a workbox based example, but in essence I'd say that's out of scope for the docs of this plugin. If you were to do that, you would then be bound to keep the example updated as Workbox is developed further. 

Tbh, the example as it is is already rather advanced. I'd probably have kept is limited to pre-caching what's in the manifest, responding with cached resources, and for the rest providing a link to a list of good resources about ServiceWorker (basically the docs at MDN, and whatever Jake Archibald has written).

**Comment by woutervanvliet** [comment]
Without further reasoning on why looking in a specific cache is a good idea, I'm closing this PR. IMHO it's too specific for the scope of the default example.

**Pull request closed without merging**
