### PR TITLE
Compute filename with [hash] pattern according to asset-path plugin

### PR DESCRIPTION
**Pull request by celiolatorraca**
Giving possibility to use webpack `asset-path` plugin pattern in filename.

So that we can now use patterns like:
```js
new ServiceWorkerPlugin({
  entry: path.join(rootDir, 'src/client/service-worker.js'),
  filename: 'sw-[hash:7].js'
}),
```

I've used `html-webpack-plugin` as reference (https://github.com/jantimon/html-webpack-plugin/blob/62c9e70113cbd921a9ca8d470cc7a149e361d0e9/lib/compiler.js#L80).

### CODE REVIEW

**Comment by oliviertassinari** [comment]
You can read this thread for more detail: https://github.com/NekR/offline-plugin/issues/127.

**Comment by celiolatorraca** [comment]
Thanks for those links explaining why it is a bad pattern changing SW file name.

This one was the most helpful (https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/lifecycle#avoid_changing_the_url_of_your_service_worker_script).

The idea here was that all my assets are hosted in a CDN, but SW has to be served on our own domain. So, I've tried to use [hash] pattern to update SW script file when changed. With that, I would be able to apply cache as my other assets.

But that's the problem. Every different SW URL is considered a new SW registration...

I'm closing this PR, thanks for your time!

**Comment by oliviertassinari** [comment]
What do you think of adding a warning if such pattern is detected with your ressource?

**Comment by celiolatorraca** [comment]
What you mean by adding a warning?

Probably I'll have to serve this file through my server instead of serving it from CDN. Even worse with no cache... Leaving SW to handle its update.
My application is entirely based on caching assets and xhrs. Probably I'll have to upscale a little my infra to do so.

**Comment by oliviertassinari** [comment]
We could warn when someone try to use `[hash`. I guess it's a common enough pattern in webpack to see people trying to use it.

**Comment by celiolatorraca** [comment]
Ohh see!

Good idea! I can send you a PR with this improve if you want...

**Comment by oliviertassinari** [comment]
I would love that :)

**Pull request closed without merging**
